/* eslint-disable */
import {
  CollectionCustomizer,
  TAggregation,
  TConditionTree,
  TPaginatedFilter,
  TPartialRow,
  TSortClause
} from '@forestadmin/agent';

export type AreaCustomizer = CollectionCustomizer<Schema, 'area'>;
export type AreaRecord = TPartialRow<Schema, 'area'>;
export type AreaConditionTree = TConditionTree<Schema, 'area'>;
export type AreaFilter = TPaginatedFilter<Schema, 'area'>;
export type AreaSortClause = TSortClause<Schema, 'area'>;
export type AreaAggregation = TAggregation<Schema, 'area'>;

export type ArticlesCustomizer = CollectionCustomizer<Schema, 'articles'>;
export type ArticlesRecord = TPartialRow<Schema, 'articles'>;
export type ArticlesConditionTree = TConditionTree<Schema, 'articles'>;
export type ArticlesFilter = TPaginatedFilter<Schema, 'articles'>;
export type ArticlesSortClause = TSortClause<Schema, 'articles'>;
export type ArticlesAggregation = TAggregation<Schema, 'articles'>;

export type CityCustomizer = CollectionCustomizer<Schema, 'city'>;
export type CityRecord = TPartialRow<Schema, 'city'>;
export type CityConditionTree = TConditionTree<Schema, 'city'>;
export type CityFilter = TPaginatedFilter<Schema, 'city'>;
export type CitySortClause = TSortClause<Schema, 'city'>;
export type CityAggregation = TAggregation<Schema, 'city'>;

export type EditorsCustomizer = CollectionCustomizer<Schema, 'editors'>;
export type EditorsRecord = TPartialRow<Schema, 'editors'>;
export type EditorsConditionTree = TConditionTree<Schema, 'editors'>;
export type EditorsFilter = TPaginatedFilter<Schema, 'editors'>;
export type EditorsSortClause = TSortClause<Schema, 'editors'>;
export type EditorsAggregation = TAggregation<Schema, 'editors'>;

export type OwnersCustomizer = CollectionCustomizer<Schema, 'owners'>;
export type OwnersRecord = TPartialRow<Schema, 'owners'>;
export type OwnersConditionTree = TConditionTree<Schema, 'owners'>;
export type OwnersFilter = TPaginatedFilter<Schema, 'owners'>;
export type OwnersSortClause = TSortClause<Schema, 'owners'>;
export type OwnersAggregation = TAggregation<Schema, 'owners'>;


export type Schema = {
  'area': {
    plain: {
      'id': number;
      'name': string;
      'test': Array<string>;
    };
    nested: {};
    flat: {};
  };
  'articles': {
    plain: {
      'assignee': string;
      'body': string;
      'created_at': string;
      'id': number;
      'is_blocked': boolean;
      'owner_id': number;
      'reason': string;
      'title': string;
      'updated_at': string;
    };
    nested: {
      'owner': Schema['owners']['plain'] & Schema['owners']['nested'];
    };
    flat: {
      'owner:createdAt': string;
      'owner:deletedAt': string;
      'owner:editorId': number;
      'owner:extraInfo': any;
      'owner:favoriteArticleId': number;
      'owner:id': number;
      'owner:name': string;
      'owner:reasons': any;
      'owner:testId': number;
      'owner:thumbs': Array<{'thumbs': Array<string>; 'uuid': number}>;
      'owner:updatedAt': string;
      'owner:editor:area_id': number;
      'owner:editor:city_id': number;
      'owner:editor:favoriteArticleId': number;
      'owner:editor:file': string;
      'owner:editor:id': number;
      'owner:editor:name': string;
      'owner:editor:startTime': string;
      'owner:favoriteArticle:assignee': string;
      'owner:favoriteArticle:body': string;
      'owner:favoriteArticle:created_at': string;
      'owner:favoriteArticle:id': number;
      'owner:favoriteArticle:is_blocked': boolean;
      'owner:favoriteArticle:owner_id': number;
      'owner:favoriteArticle:reason': string;
      'owner:favoriteArticle:title': string;
      'owner:favoriteArticle:updated_at': string;
      'owner:editor:area:id': number;
      'owner:editor:area:name': string;
      'owner:editor:area:test': Array<string>;
      'owner:editor:city:area_id': number;
      'owner:editor:city:id': number;
      'owner:editor:city:name': string;
      'owner:editor:favoriteArticle:assignee': string;
      'owner:editor:favoriteArticle:body': string;
      'owner:editor:favoriteArticle:created_at': string;
      'owner:editor:favoriteArticle:id': number;
      'owner:editor:favoriteArticle:is_blocked': boolean;
      'owner:editor:favoriteArticle:owner_id': number;
      'owner:editor:favoriteArticle:reason': string;
      'owner:editor:favoriteArticle:title': string;
      'owner:editor:favoriteArticle:updated_at': string;
      'owner:favoriteArticle:owner:createdAt': string;
      'owner:favoriteArticle:owner:deletedAt': string;
      'owner:favoriteArticle:owner:editorId': number;
      'owner:favoriteArticle:owner:extraInfo': any;
      'owner:favoriteArticle:owner:favoriteArticleId': number;
      'owner:favoriteArticle:owner:id': number;
      'owner:favoriteArticle:owner:name': string;
      'owner:favoriteArticle:owner:reasons': any;
      'owner:favoriteArticle:owner:testId': number;
      'owner:favoriteArticle:owner:thumbs': Array<{'thumbs': Array<string>; 'uuid': number}>;
      'owner:favoriteArticle:owner:updatedAt': string;
      'owner:editor:city:area:id': number;
      'owner:editor:city:area:name': string;
      'owner:editor:city:area:test': Array<string>;
      'owner:editor:favoriteArticle:owner:createdAt': string;
      'owner:editor:favoriteArticle:owner:deletedAt': string;
      'owner:editor:favoriteArticle:owner:editorId': number;
      'owner:editor:favoriteArticle:owner:extraInfo': any;
      'owner:editor:favoriteArticle:owner:favoriteArticleId': number;
      'owner:editor:favoriteArticle:owner:id': number;
      'owner:editor:favoriteArticle:owner:name': string;
      'owner:editor:favoriteArticle:owner:reasons': any;
      'owner:editor:favoriteArticle:owner:testId': number;
      'owner:editor:favoriteArticle:owner:thumbs': Array<{'thumbs': Array<string>; 'uuid': number}>;
      'owner:editor:favoriteArticle:owner:updatedAt': string;
      'owner:favoriteArticle:owner:editor:area_id': number;
      'owner:favoriteArticle:owner:editor:city_id': number;
      'owner:favoriteArticle:owner:editor:favoriteArticleId': number;
      'owner:favoriteArticle:owner:editor:file': string;
      'owner:favoriteArticle:owner:editor:id': number;
      'owner:favoriteArticle:owner:editor:name': string;
      'owner:favoriteArticle:owner:editor:startTime': string;
      'owner:favoriteArticle:owner:favoriteArticle:assignee': string;
      'owner:favoriteArticle:owner:favoriteArticle:body': string;
      'owner:favoriteArticle:owner:favoriteArticle:created_at': string;
      'owner:favoriteArticle:owner:favoriteArticle:id': number;
      'owner:favoriteArticle:owner:favoriteArticle:is_blocked': boolean;
      'owner:favoriteArticle:owner:favoriteArticle:owner_id': number;
      'owner:favoriteArticle:owner:favoriteArticle:reason': string;
      'owner:favoriteArticle:owner:favoriteArticle:title': string;
      'owner:favoriteArticle:owner:favoriteArticle:updated_at': string;
      'owner:editor:favoriteArticle:owner:editor:area_id': number;
      'owner:editor:favoriteArticle:owner:editor:city_id': number;
      'owner:editor:favoriteArticle:owner:editor:favoriteArticleId': number;
      'owner:editor:favoriteArticle:owner:editor:file': string;
      'owner:editor:favoriteArticle:owner:editor:id': number;
      'owner:editor:favoriteArticle:owner:editor:name': string;
      'owner:editor:favoriteArticle:owner:editor:startTime': string;
      'owner:editor:favoriteArticle:owner:favoriteArticle:assignee': string;
      'owner:editor:favoriteArticle:owner:favoriteArticle:body': string;
      'owner:editor:favoriteArticle:owner:favoriteArticle:created_at': string;
      'owner:editor:favoriteArticle:owner:favoriteArticle:id': number;
      'owner:editor:favoriteArticle:owner:favoriteArticle:is_blocked': boolean;
      'owner:editor:favoriteArticle:owner:favoriteArticle:owner_id': number;
      'owner:editor:favoriteArticle:owner:favoriteArticle:reason': string;
      'owner:editor:favoriteArticle:owner:favoriteArticle:title': string;
      'owner:editor:favoriteArticle:owner:favoriteArticle:updated_at': string;
      'owner:favoriteArticle:owner:editor:area:id': number;
      'owner:favoriteArticle:owner:editor:area:name': string;
      'owner:favoriteArticle:owner:editor:area:test': Array<string>;
      'owner:favoriteArticle:owner:editor:city:area_id': number;
      'owner:favoriteArticle:owner:editor:city:id': number;
      'owner:favoriteArticle:owner:editor:city:name': string;
      'owner:favoriteArticle:owner:editor:favoriteArticle:assignee': string;
      'owner:favoriteArticle:owner:editor:favoriteArticle:body': string;
      'owner:favoriteArticle:owner:editor:favoriteArticle:created_at': string;
      'owner:favoriteArticle:owner:editor:favoriteArticle:id': number;
      'owner:favoriteArticle:owner:editor:favoriteArticle:is_blocked': boolean;
      'owner:favoriteArticle:owner:editor:favoriteArticle:owner_id': number;
      'owner:favoriteArticle:owner:editor:favoriteArticle:reason': string;
      'owner:favoriteArticle:owner:editor:favoriteArticle:title': string;
      'owner:favoriteArticle:owner:editor:favoriteArticle:updated_at': string;
      'owner:favoriteArticle:owner:favoriteArticle:owner:createdAt': string;
      'owner:favoriteArticle:owner:favoriteArticle:owner:deletedAt': string;
      'owner:favoriteArticle:owner:favoriteArticle:owner:editorId': number;
      'owner:favoriteArticle:owner:favoriteArticle:owner:extraInfo': any;
      'owner:favoriteArticle:owner:favoriteArticle:owner:favoriteArticleId': number;
      'owner:favoriteArticle:owner:favoriteArticle:owner:id': number;
      'owner:favoriteArticle:owner:favoriteArticle:owner:name': string;
      'owner:favoriteArticle:owner:favoriteArticle:owner:reasons': any;
      'owner:favoriteArticle:owner:favoriteArticle:owner:testId': number;
      'owner:favoriteArticle:owner:favoriteArticle:owner:thumbs': Array<{'thumbs': Array<string>; 'uuid': number}>;
      'owner:favoriteArticle:owner:favoriteArticle:owner:updatedAt': string;
    };
  };
  'city': {
    plain: {
      'area_id': number;
      'id': number;
      'name': string;
    };
    nested: {
      'area': Schema['area']['plain'] & Schema['area']['nested'];
    };
    flat: {
      'area:id': number;
      'area:name': string;
      'area:test': Array<string>;
    };
  };
  'editors': {
    plain: {
      'area_id': number;
      'city_id': number;
      'favoriteArticleId': number;
      'file': string;
      'id': number;
      'name': string;
      'startTime': string;
    };
    nested: {
      'area': Schema['area']['plain'] & Schema['area']['nested'];
      'city': Schema['city']['plain'] & Schema['city']['nested'];
      'favoriteArticle': Schema['articles']['plain'] & Schema['articles']['nested'];
    };
    flat: {
      'area:id': number;
      'area:name': string;
      'area:test': Array<string>;
      'city:area_id': number;
      'city:id': number;
      'city:name': string;
      'favoriteArticle:assignee': string;
      'favoriteArticle:body': string;
      'favoriteArticle:created_at': string;
      'favoriteArticle:id': number;
      'favoriteArticle:is_blocked': boolean;
      'favoriteArticle:owner_id': number;
      'favoriteArticle:reason': string;
      'favoriteArticle:title': string;
      'favoriteArticle:updated_at': string;
      'city:area:id': number;
      'city:area:name': string;
      'city:area:test': Array<string>;
      'favoriteArticle:owner:createdAt': string;
      'favoriteArticle:owner:deletedAt': string;
      'favoriteArticle:owner:editorId': number;
      'favoriteArticle:owner:extraInfo': any;
      'favoriteArticle:owner:favoriteArticleId': number;
      'favoriteArticle:owner:id': number;
      'favoriteArticle:owner:name': string;
      'favoriteArticle:owner:reasons': any;
      'favoriteArticle:owner:testId': number;
      'favoriteArticle:owner:thumbs': Array<{'thumbs': Array<string>; 'uuid': number}>;
      'favoriteArticle:owner:updatedAt': string;
      'favoriteArticle:owner:editor:area_id': number;
      'favoriteArticle:owner:editor:city_id': number;
      'favoriteArticle:owner:editor:favoriteArticleId': number;
      'favoriteArticle:owner:editor:file': string;
      'favoriteArticle:owner:editor:id': number;
      'favoriteArticle:owner:editor:name': string;
      'favoriteArticle:owner:editor:startTime': string;
      'favoriteArticle:owner:favoriteArticle:assignee': string;
      'favoriteArticle:owner:favoriteArticle:body': string;
      'favoriteArticle:owner:favoriteArticle:created_at': string;
      'favoriteArticle:owner:favoriteArticle:id': number;
      'favoriteArticle:owner:favoriteArticle:is_blocked': boolean;
      'favoriteArticle:owner:favoriteArticle:owner_id': number;
      'favoriteArticle:owner:favoriteArticle:reason': string;
      'favoriteArticle:owner:favoriteArticle:title': string;
      'favoriteArticle:owner:favoriteArticle:updated_at': string;
      'favoriteArticle:owner:editor:area:id': number;
      'favoriteArticle:owner:editor:area:name': string;
      'favoriteArticle:owner:editor:area:test': Array<string>;
      'favoriteArticle:owner:editor:city:area_id': number;
      'favoriteArticle:owner:editor:city:id': number;
      'favoriteArticle:owner:editor:city:name': string;
      'favoriteArticle:owner:editor:favoriteArticle:assignee': string;
      'favoriteArticle:owner:editor:favoriteArticle:body': string;
      'favoriteArticle:owner:editor:favoriteArticle:created_at': string;
      'favoriteArticle:owner:editor:favoriteArticle:id': number;
      'favoriteArticle:owner:editor:favoriteArticle:is_blocked': boolean;
      'favoriteArticle:owner:editor:favoriteArticle:owner_id': number;
      'favoriteArticle:owner:editor:favoriteArticle:reason': string;
      'favoriteArticle:owner:editor:favoriteArticle:title': string;
      'favoriteArticle:owner:editor:favoriteArticle:updated_at': string;
      'favoriteArticle:owner:favoriteArticle:owner:createdAt': string;
      'favoriteArticle:owner:favoriteArticle:owner:deletedAt': string;
      'favoriteArticle:owner:favoriteArticle:owner:editorId': number;
      'favoriteArticle:owner:favoriteArticle:owner:extraInfo': any;
      'favoriteArticle:owner:favoriteArticle:owner:favoriteArticleId': number;
      'favoriteArticle:owner:favoriteArticle:owner:id': number;
      'favoriteArticle:owner:favoriteArticle:owner:name': string;
      'favoriteArticle:owner:favoriteArticle:owner:reasons': any;
      'favoriteArticle:owner:favoriteArticle:owner:testId': number;
      'favoriteArticle:owner:favoriteArticle:owner:thumbs': Array<{'thumbs': Array<string>; 'uuid': number}>;
      'favoriteArticle:owner:favoriteArticle:owner:updatedAt': string;
      'favoriteArticle:owner:editor:city:area:id': number;
      'favoriteArticle:owner:editor:city:area:name': string;
      'favoriteArticle:owner:editor:city:area:test': Array<string>;
      'favoriteArticle:owner:editor:favoriteArticle:owner:createdAt': string;
      'favoriteArticle:owner:editor:favoriteArticle:owner:deletedAt': string;
      'favoriteArticle:owner:editor:favoriteArticle:owner:editorId': number;
      'favoriteArticle:owner:editor:favoriteArticle:owner:extraInfo': any;
      'favoriteArticle:owner:editor:favoriteArticle:owner:favoriteArticleId': number;
      'favoriteArticle:owner:editor:favoriteArticle:owner:id': number;
      'favoriteArticle:owner:editor:favoriteArticle:owner:name': string;
      'favoriteArticle:owner:editor:favoriteArticle:owner:reasons': any;
      'favoriteArticle:owner:editor:favoriteArticle:owner:testId': number;
      'favoriteArticle:owner:editor:favoriteArticle:owner:thumbs': Array<{'thumbs': Array<string>; 'uuid': number}>;
      'favoriteArticle:owner:editor:favoriteArticle:owner:updatedAt': string;
      'favoriteArticle:owner:favoriteArticle:owner:editor:area_id': number;
      'favoriteArticle:owner:favoriteArticle:owner:editor:city_id': number;
      'favoriteArticle:owner:favoriteArticle:owner:editor:favoriteArticleId': number;
      'favoriteArticle:owner:favoriteArticle:owner:editor:file': string;
      'favoriteArticle:owner:favoriteArticle:owner:editor:id': number;
      'favoriteArticle:owner:favoriteArticle:owner:editor:name': string;
      'favoriteArticle:owner:favoriteArticle:owner:editor:startTime': string;
      'favoriteArticle:owner:favoriteArticle:owner:favoriteArticle:assignee': string;
      'favoriteArticle:owner:favoriteArticle:owner:favoriteArticle:body': string;
      'favoriteArticle:owner:favoriteArticle:owner:favoriteArticle:created_at': string;
      'favoriteArticle:owner:favoriteArticle:owner:favoriteArticle:id': number;
      'favoriteArticle:owner:favoriteArticle:owner:favoriteArticle:is_blocked': boolean;
      'favoriteArticle:owner:favoriteArticle:owner:favoriteArticle:owner_id': number;
      'favoriteArticle:owner:favoriteArticle:owner:favoriteArticle:reason': string;
      'favoriteArticle:owner:favoriteArticle:owner:favoriteArticle:title': string;
      'favoriteArticle:owner:favoriteArticle:owner:favoriteArticle:updated_at': string;
    };
  };
  'owners': {
    plain: {
      'createdAt': string;
      'deletedAt': string;
      'editorId': number;
      'extraInfo': any;
      'favoriteArticleId': number;
      'id': number;
      'name': string;
      'reasons': any;
      'testId': number;
      'thumbs': Array<{'thumbs': Array<string>; 'uuid': number}>;
      'updatedAt': string;
    };
    nested: {
      'editor': Schema['editors']['plain'] & Schema['editors']['nested'];
      'favoriteArticle': Schema['articles']['plain'] & Schema['articles']['nested'];
    };
    flat: {
      'editor:area_id': number;
      'editor:city_id': number;
      'editor:favoriteArticleId': number;
      'editor:file': string;
      'editor:id': number;
      'editor:name': string;
      'editor:startTime': string;
      'favoriteArticle:assignee': string;
      'favoriteArticle:body': string;
      'favoriteArticle:created_at': string;
      'favoriteArticle:id': number;
      'favoriteArticle:is_blocked': boolean;
      'favoriteArticle:owner_id': number;
      'favoriteArticle:reason': string;
      'favoriteArticle:title': string;
      'favoriteArticle:updated_at': string;
      'editor:area:id': number;
      'editor:area:name': string;
      'editor:area:test': Array<string>;
      'editor:city:area_id': number;
      'editor:city:id': number;
      'editor:city:name': string;
      'editor:favoriteArticle:assignee': string;
      'editor:favoriteArticle:body': string;
      'editor:favoriteArticle:created_at': string;
      'editor:favoriteArticle:id': number;
      'editor:favoriteArticle:is_blocked': boolean;
      'editor:favoriteArticle:owner_id': number;
      'editor:favoriteArticle:reason': string;
      'editor:favoriteArticle:title': string;
      'editor:favoriteArticle:updated_at': string;
      'favoriteArticle:owner:createdAt': string;
      'favoriteArticle:owner:deletedAt': string;
      'favoriteArticle:owner:editorId': number;
      'favoriteArticle:owner:extraInfo': any;
      'favoriteArticle:owner:favoriteArticleId': number;
      'favoriteArticle:owner:id': number;
      'favoriteArticle:owner:name': string;
      'favoriteArticle:owner:reasons': any;
      'favoriteArticle:owner:testId': number;
      'favoriteArticle:owner:thumbs': Array<{'thumbs': Array<string>; 'uuid': number}>;
      'favoriteArticle:owner:updatedAt': string;
      'editor:city:area:id': number;
      'editor:city:area:name': string;
      'editor:city:area:test': Array<string>;
      'editor:favoriteArticle:owner:createdAt': string;
      'editor:favoriteArticle:owner:deletedAt': string;
      'editor:favoriteArticle:owner:editorId': number;
      'editor:favoriteArticle:owner:extraInfo': any;
      'editor:favoriteArticle:owner:favoriteArticleId': number;
      'editor:favoriteArticle:owner:id': number;
      'editor:favoriteArticle:owner:name': string;
      'editor:favoriteArticle:owner:reasons': any;
      'editor:favoriteArticle:owner:testId': number;
      'editor:favoriteArticle:owner:thumbs': Array<{'thumbs': Array<string>; 'uuid': number}>;
      'editor:favoriteArticle:owner:updatedAt': string;
      'favoriteArticle:owner:editor:area_id': number;
      'favoriteArticle:owner:editor:city_id': number;
      'favoriteArticle:owner:editor:favoriteArticleId': number;
      'favoriteArticle:owner:editor:file': string;
      'favoriteArticle:owner:editor:id': number;
      'favoriteArticle:owner:editor:name': string;
      'favoriteArticle:owner:editor:startTime': string;
      'favoriteArticle:owner:favoriteArticle:assignee': string;
      'favoriteArticle:owner:favoriteArticle:body': string;
      'favoriteArticle:owner:favoriteArticle:created_at': string;
      'favoriteArticle:owner:favoriteArticle:id': number;
      'favoriteArticle:owner:favoriteArticle:is_blocked': boolean;
      'favoriteArticle:owner:favoriteArticle:owner_id': number;
      'favoriteArticle:owner:favoriteArticle:reason': string;
      'favoriteArticle:owner:favoriteArticle:title': string;
      'favoriteArticle:owner:favoriteArticle:updated_at': string;
      'editor:favoriteArticle:owner:editor:area_id': number;
      'editor:favoriteArticle:owner:editor:city_id': number;
      'editor:favoriteArticle:owner:editor:favoriteArticleId': number;
      'editor:favoriteArticle:owner:editor:file': string;
      'editor:favoriteArticle:owner:editor:id': number;
      'editor:favoriteArticle:owner:editor:name': string;
      'editor:favoriteArticle:owner:editor:startTime': string;
      'editor:favoriteArticle:owner:favoriteArticle:assignee': string;
      'editor:favoriteArticle:owner:favoriteArticle:body': string;
      'editor:favoriteArticle:owner:favoriteArticle:created_at': string;
      'editor:favoriteArticle:owner:favoriteArticle:id': number;
      'editor:favoriteArticle:owner:favoriteArticle:is_blocked': boolean;
      'editor:favoriteArticle:owner:favoriteArticle:owner_id': number;
      'editor:favoriteArticle:owner:favoriteArticle:reason': string;
      'editor:favoriteArticle:owner:favoriteArticle:title': string;
      'editor:favoriteArticle:owner:favoriteArticle:updated_at': string;
      'favoriteArticle:owner:editor:area:id': number;
      'favoriteArticle:owner:editor:area:name': string;
      'favoriteArticle:owner:editor:area:test': Array<string>;
      'favoriteArticle:owner:editor:city:area_id': number;
      'favoriteArticle:owner:editor:city:id': number;
      'favoriteArticle:owner:editor:city:name': string;
      'favoriteArticle:owner:editor:favoriteArticle:assignee': string;
      'favoriteArticle:owner:editor:favoriteArticle:body': string;
      'favoriteArticle:owner:editor:favoriteArticle:created_at': string;
      'favoriteArticle:owner:editor:favoriteArticle:id': number;
      'favoriteArticle:owner:editor:favoriteArticle:is_blocked': boolean;
      'favoriteArticle:owner:editor:favoriteArticle:owner_id': number;
      'favoriteArticle:owner:editor:favoriteArticle:reason': string;
      'favoriteArticle:owner:editor:favoriteArticle:title': string;
      'favoriteArticle:owner:editor:favoriteArticle:updated_at': string;
      'favoriteArticle:owner:favoriteArticle:owner:createdAt': string;
      'favoriteArticle:owner:favoriteArticle:owner:deletedAt': string;
      'favoriteArticle:owner:favoriteArticle:owner:editorId': number;
      'favoriteArticle:owner:favoriteArticle:owner:extraInfo': any;
      'favoriteArticle:owner:favoriteArticle:owner:favoriteArticleId': number;
      'favoriteArticle:owner:favoriteArticle:owner:id': number;
      'favoriteArticle:owner:favoriteArticle:owner:name': string;
      'favoriteArticle:owner:favoriteArticle:owner:reasons': any;
      'favoriteArticle:owner:favoriteArticle:owner:testId': number;
      'favoriteArticle:owner:favoriteArticle:owner:thumbs': Array<{'thumbs': Array<string>; 'uuid': number}>;
      'favoriteArticle:owner:favoriteArticle:owner:updatedAt': string;
      'editor:favoriteArticle:owner:editor:area:id': number;
      'editor:favoriteArticle:owner:editor:area:name': string;
      'editor:favoriteArticle:owner:editor:area:test': Array<string>;
      'editor:favoriteArticle:owner:editor:city:area_id': number;
      'editor:favoriteArticle:owner:editor:city:id': number;
      'editor:favoriteArticle:owner:editor:city:name': string;
      'editor:favoriteArticle:owner:editor:favoriteArticle:assignee': string;
      'editor:favoriteArticle:owner:editor:favoriteArticle:body': string;
      'editor:favoriteArticle:owner:editor:favoriteArticle:created_at': string;
      'editor:favoriteArticle:owner:editor:favoriteArticle:id': number;
      'editor:favoriteArticle:owner:editor:favoriteArticle:is_blocked': boolean;
      'editor:favoriteArticle:owner:editor:favoriteArticle:owner_id': number;
      'editor:favoriteArticle:owner:editor:favoriteArticle:reason': string;
      'editor:favoriteArticle:owner:editor:favoriteArticle:title': string;
      'editor:favoriteArticle:owner:editor:favoriteArticle:updated_at': string;
      'editor:favoriteArticle:owner:favoriteArticle:owner:createdAt': string;
      'editor:favoriteArticle:owner:favoriteArticle:owner:deletedAt': string;
      'editor:favoriteArticle:owner:favoriteArticle:owner:editorId': number;
      'editor:favoriteArticle:owner:favoriteArticle:owner:extraInfo': any;
      'editor:favoriteArticle:owner:favoriteArticle:owner:favoriteArticleId': number;
      'editor:favoriteArticle:owner:favoriteArticle:owner:id': number;
      'editor:favoriteArticle:owner:favoriteArticle:owner:name': string;
      'editor:favoriteArticle:owner:favoriteArticle:owner:reasons': any;
      'editor:favoriteArticle:owner:favoriteArticle:owner:testId': number;
      'editor:favoriteArticle:owner:favoriteArticle:owner:thumbs': Array<{'thumbs': Array<string>; 'uuid': number}>;
      'editor:favoriteArticle:owner:favoriteArticle:owner:updatedAt': string;
      'favoriteArticle:owner:editor:city:area:id': number;
      'favoriteArticle:owner:editor:city:area:name': string;
      'favoriteArticle:owner:editor:city:area:test': Array<string>;
      'favoriteArticle:owner:editor:favoriteArticle:owner:createdAt': string;
      'favoriteArticle:owner:editor:favoriteArticle:owner:deletedAt': string;
      'favoriteArticle:owner:editor:favoriteArticle:owner:editorId': number;
      'favoriteArticle:owner:editor:favoriteArticle:owner:extraInfo': any;
      'favoriteArticle:owner:editor:favoriteArticle:owner:favoriteArticleId': number;
      'favoriteArticle:owner:editor:favoriteArticle:owner:id': number;
      'favoriteArticle:owner:editor:favoriteArticle:owner:name': string;
      'favoriteArticle:owner:editor:favoriteArticle:owner:reasons': any;
      'favoriteArticle:owner:editor:favoriteArticle:owner:testId': number;
      'favoriteArticle:owner:editor:favoriteArticle:owner:thumbs': Array<{'thumbs': Array<string>; 'uuid': number}>;
      'favoriteArticle:owner:editor:favoriteArticle:owner:updatedAt': string;
      'favoriteArticle:owner:favoriteArticle:owner:editor:area_id': number;
      'favoriteArticle:owner:favoriteArticle:owner:editor:city_id': number;
      'favoriteArticle:owner:favoriteArticle:owner:editor:favoriteArticleId': number;
      'favoriteArticle:owner:favoriteArticle:owner:editor:file': string;
      'favoriteArticle:owner:favoriteArticle:owner:editor:id': number;
      'favoriteArticle:owner:favoriteArticle:owner:editor:name': string;
      'favoriteArticle:owner:favoriteArticle:owner:editor:startTime': string;
      'favoriteArticle:owner:favoriteArticle:owner:favoriteArticle:assignee': string;
      'favoriteArticle:owner:favoriteArticle:owner:favoriteArticle:body': string;
      'favoriteArticle:owner:favoriteArticle:owner:favoriteArticle:created_at': string;
      'favoriteArticle:owner:favoriteArticle:owner:favoriteArticle:id': number;
      'favoriteArticle:owner:favoriteArticle:owner:favoriteArticle:is_blocked': boolean;
      'favoriteArticle:owner:favoriteArticle:owner:favoriteArticle:owner_id': number;
      'favoriteArticle:owner:favoriteArticle:owner:favoriteArticle:reason': string;
      'favoriteArticle:owner:favoriteArticle:owner:favoriteArticle:title': string;
      'favoriteArticle:owner:favoriteArticle:owner:favoriteArticle:updated_at': string;
    };
  };
};
